import{S as d,a as f,i as p,b as m}from"./assets/vendor-DtJgfVVA.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const a=document.querySelector(".js-backdrop"),h={lines:8,length:33,width:4,radius:26,scale:.6,corners:.5,speed:1.6,rotate:0,animation:"spinner-line-fade-quick",direction:1,color:"#ffffff",fadeColor:"transparent",top:"49%",left:"50%",shadow:"0 0 1px transparent",zIndex:2e9,className:"spinner",position:"absolute"},u=new d(h),g=()=>{a.classList.remove("is-hidden"),u.spin(a)},c=()=>{a.classList.add("is-hidden"),u.stop()},y="https://pixabay.com/api/",L="41741201-12a642cf53882fe64e8e82723",b=n=>{const e=`${y}?key=${L}&q=${n}&image_type=photo&orientation=horizontal&safesearch=true`;return f.get(e).then(s=>{const o=s.data;return o.total===0&&p.info({position:"center",message:"Sorry, there are no images matching your search query. Please try again!"}),o}).catch(s=>{throw s.response?new Error(`Response is not success: ${s.response.status}`):s})},w=n=>n.map(e=>`<div class="img-item">
        <a href="${e.largeImageURL}" class="lightbox-link">
          <img src="${e.webformatURL}" alt="${e.tags}">
        </a>
        <div class="image-info">
          <p>Likes: ${e.likes}</p>
          <p>Views: ${e.views}</p>
          <p>Comments: ${e.comments}</p>
          <p>Downloads: ${e.downloads}</p>
        </div>
      </div>`).join(""),l=document.querySelector(".img-list"),S=document.querySelector(".form"),v=document.querySelector(".input"),$=n=>{n.preventDefault(),g();const e=n.currentTarget.elements.query.value.trim();if(l.innerHTML="",e!=="")b(e).then(s=>{l.innerHTML=w(s.hits),new m(".lightbox-link").refresh()}).catch(s=>{console.error(s)}).finally(()=>{c(),v.value=""});else return c(),p.warning({position:"center",message:"Please enter a search query."})};S.addEventListener("submit",$);
//# sourceMappingURL=index.js.map
