import{S as d,a as f,i as p,b as m}from"./assets/vendor-DtJgfVVA.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();const a=document.querySelector(".js-backdrop"),h={lines:8,length:33,width:4,radius:26,scale:.6,corners:.5,speed:1.6,rotate:0,animation:"spinner-line-fade-quick",direction:1,color:"#ffffff",fadeColor:"transparent",top:"49%",left:"50%",shadow:"0 0 1px transparent",zIndex:2e9,className:"spinner",position:"absolute"},u=new d(h),y=()=>{a.classList.remove("is-hidden"),u.spin(a)},c=()=>{a.classList.add("is-hidden"),u.stop()},g="https://pixabay.com/api/",b="41741201-12a642cf53882fe64e8e82723",L=n=>{const e=`${g}?key=${b}&q=${n}&image_type=photo&orientation=horizontal&safesearch=true`;return f.get(e).then(r=>{const o=r.data;return o.total===0&&p.info({position:"center",message:"Sorry, there are no images matching your search query. Please try again!"}),o}).catch(r=>{throw r.response?new Error(`Response is not success: ${r.response.status}`):r})},w=n=>n.map(e=>`<div class="img-item">
        <a href="${e.largeImageURL}" class="lightbox-link">
          <img src="${e.webformatURL}" alt="${e.tags}">
        </a>
        <div class="image-info">
          <p>Likes: ${e.likes}</p>
          <p>Views: ${e.views}</p>
          <p>Comments: ${e.comments}</p>
          <p>Downloads: ${e.downloads}</p>
        </div>
      </div>`).join(""),l=document.querySelector(".gallery"),S=document.querySelector(".form"),v=document.querySelector(".input"),$=n=>{n.preventDefault(),y();const e=n.currentTarget.elements.query.value.trim();if(l.innerHTML="",e!=="")L(e).then(r=>{l.innerHTML=w(r.hits),new m(".lightbox-link").refresh()}).catch(r=>{console.error(r)}).finally(()=>{c(),v.value=""});else return c(),p.warning({position:"center",message:"Please enter a search query."})};S.addEventListener("submit",$);
//# sourceMappingURL=index.js.map
