import{S as f,i as u,a as d}from"./assets/vendor-CM8htHIk.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const i of n.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function r(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function o(t){if(t.ep)return;t.ep=!0;const n=r(t);fetch(t.href,n)}})();const c=document.querySelector(".js-backdrop"),m={lines:8,length:33,width:4,radius:26,scale:.6,corners:.5,speed:1.6,rotate:0,animation:"spinner-line-fade-quick",direction:1,color:"#ffffff",fadeColor:"transparent",top:"49%",left:"50%",shadow:"0 0 1px transparent",zIndex:2e9,className:"spinner",position:"absolute"},p=new f(m),h=()=>{c.classList.remove("is-hidden"),p.spin(c)},a=()=>{c.classList.add("is-hidden"),p.stop()},y="https://pixabay.com/api/",g="41741201-12a642cf53882fe64e8e82723",L=s=>{const e=`${y}?key=${g}&q=${s}&image_type=photo&orientation=horizontal&safesearch=true`;return fetch(e).then(r=>{if(!r.ok)throw new Error(`Response is not success: ${r.status}`);return r.json()}).then(r=>(r.total===0&&u.info({position:"center",message:"Sorry, there are no images matching your search query. Please try again!"}),r))},b=s=>s.map(e=>`<div class="img-item">
        <a href="${e.largeImageURL}" class="lightbox-link">
          <img src="${e.webformatURL}" alt="${e.tags}">
        </a>
        <div class="image-info">
          <p>Likes: ${e.likes}</p>
          <p>Views: ${e.views}</p>
          <p>Comments: ${e.comments}</p>
          <p>Downloads: ${e.downloads}</p>
        </div>
      </div>`).join(""),l=document.querySelector(".img-container"),w=document.querySelector(".search-form"),S=document.querySelector(".search-input"),v=s=>{s.preventDefault(),h();const e=s.currentTarget.elements.query.value.trim();if(l.innerHTML="",e!=="")L(e).then(r=>{l.innerHTML=b(r.hits),new d(".lightbox-link").refresh()}).catch(r=>{console.error(r)}).finally(()=>{a(),S.value=""});else return a(),u.warning({position:"center",message:"Please enter a search query."})};w.addEventListener("submit",v);
//# sourceMappingURL=index.js.map
